version: '3.8'
services:
    mysql_db:
        image: mysql
        platform: linux/x86_64
        environment:
            MYSQL_DATABASE: 'bookstore'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'pass'
            MYSQL_ROOT_PASSWORD: 'pass'
        ports:
            - '3306:3306'
        expose:
            - 3306
        volumes:
            - ./data:/var/lib/mysql
